version: '20'

services:
  app:
    container_name: netmon-mvp
    restart: always
    build: .
    ports:
      - '1819:3000'
      #   ^host ^container
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "2587:27017"